apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  log_level: "verbose"
  logging_test: "abc test 1"
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "printenv"]
      image: busybox:latest
      env:
        - name: logging_mode
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: log_level
        - name: logging_test
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: logging_test