apiVersion: v1
kind: Secret
metadata:
  name: test
type: Opaque
data:
  password: dGVzdC1wYXNzd29yZA==
  username: dGVzdC11c2VybmFtZQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: test
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: test
            key: password
  restartPolicy: Never