apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpdd:latest
        volumeMounts:
        - name: httpd-storage
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: httpd-storage
        persistentVolumeClaim:
          claimName: httpd2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: htttpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: test-app2.rancher.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpd-service
            port:
              number: 80