apiVersion: v1
kind: LimitRange
metadata:
  name: default-lr
spec:
  limits:
    - default:
        cpu: 500m
        memory: 500Mi
      defaultRequest:
        cpu: 250m
        memory: 250Mi
      max:
        cpu: "1"
      min:
        cpu: 100m
      type: Container